#!/bin/bash
#SBATCH --job-name=numt_coverage
#SBATCH --account=kdm16_sc_default
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=2
#SBATCH --mem=16G
#SBATCH --time=8:00:00
#SBATCH --output=logs/cover_%j.log

set -eux

# Create log directory if it doesn't exist
mkdir -p logs

# Initialize micromamba
export MAMBA_ROOT_PREFIX="/storage/home/ejt89"
eval "$($MAMBA_ROOT_PREFIX/bin/micromamba shell hook -s bash)"

# Activate the specific environment
micromamba activate bioinfo

NUMTS="numts.mPonPyg2.pri.bed"
BAM_DIR="/scratch/ejt89/apes_output/alignments"
BAM="PonPyg_male_Dennis_SRR033344_t2t.bam"
COV="cov.$(basename $BAM .bam).txt"

bedtools sort -i $NUMTS > "sorted.$NUMTS"

# Get coverage at NUMTS sites.
#samtools bedcov $NUMTS $BAM_DIR/$BAM > "bed$COV"
bedtools coverage -a "sorted.$NUMTS" -b $BAM_DIR/$BAM -sorted > $COV 


