#!/bin/bash
#SBATCH --job-name=download_smk
#SBATCH --partition=basic
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=5
#SBATCH --mem=25G
#SBATCH --time=24:00:00
#SBATCH --output=logs/slurm/down_%j.log

# Create log directory if it doesn't exist
mkdir -p logs/slurm

# Initialize micromamba
export MAMBA_ROOT_PREFIX="/storage/home/ejt89"
eval "$($MAMBA_ROOT_PREFIX/bin/micromamba shell hook -s bash)"

# Activate the specific environment
micromamba activate download_fastq

# Clear any stale locks from previous crashes.
snakemake --unlock

# Run Snakemake.
snakemake -j 5 --rerun-incomplete

